const APP_TAGS = {
  Entity: 'ENTITY',
} as const;

const MODEL_NAMES = [
  'arrow-basic',
  'arrow',
  'box-large',
  'box-long',
  'box-small',
  'box-wide',
  'conveyor-bars-fence',
  'conveyor-bars-high',
  'conveyor-bars-sides',
  'conveyor-bars-stripe-fence',
  'conveyor-bars-stripe-high',
  'conveyor-bars-stripe-side',
  'conveyor-bars-stripe',
  'conveyor-bars',
  'conveyor-long-sides',
  'conveyor-long-stripe-sides',
  'conveyor-long-stripe',
  'conveyor-long',
  'conveyor-sides',
  'conveyor-stripe-sides',
  'conveyor-stripe',
  'conveyor',
  'cover-bar',
  'cover-corner',
  'cover-hopper',
  'cover-stripe-bar',
  'cover-stripe-corner',
  'cover-stripe-hopper',
  'cover-stripe-top',
  'cover-stripe-window',
  'cover-stripe',
  'cover-top',
  'cover-window',
  'cover',
  'door-wide-closed',
  'door-wide-half',
  'door-wide-open',
  'door',
  'floor-large',
  'floor',
  'robot-arm-a',
  'robot-arm-b',
  'scanner-high',
  'scanner-low',
  'structure-corner-inner',
  'structure-corner-outer',
  'structure-doorway-wide',
  'structure-doorway',
  'structure-high',
  'structure-medium',
  'structure-short',
  'structure-tall',
  'structure-wall',
  'structure-window-wide',
  'structure-window',
  'structure-yellow-high',
  'structure-yellow-medium',
  'structure-yellow-short',
  'structure-yellow-tall',
  'top-large',
  'top',
] as const;

export { APP_TAGS, MODEL_NAMES };
