type ModelNameMap = {
  'conveyor-kit':
    | 'arrow'
    | 'arrow-basic'
    | 'box-large'
    | 'box-long'
    | 'box-small'
    | 'box-wide'
    | 'conveyor'
    | 'conveyor-bars'
    | 'conveyor-bars-fence'
    | 'conveyor-bars-high'
    | 'conveyor-bars-sides'
    | 'conveyor-bars-stripe'
    | 'conveyor-bars-stripe-fence'
    | 'conveyor-bars-stripe-high'
    | 'conveyor-bars-stripe-side'
    | 'conveyor-long'
    | 'conveyor-long-sides'
    | 'conveyor-long-stripe'
    | 'conveyor-long-stripe-sides'
    | 'conveyor-sides'
    | 'conveyor-stripe'
    | 'conveyor-stripe-sides'
    | 'cover'
    | 'cover-bar'
    | 'cover-corner'
    | 'cover-hopper'
    | 'cover-stripe'
    | 'cover-stripe-bar'
    | 'cover-stripe-corner'
    | 'cover-stripe-hopper'
    | 'cover-stripe-top'
    | 'cover-stripe-window'
    | 'cover-top'
    | 'cover-window'
    | 'door'
    | 'door-wide-closed'
    | 'door-wide-half'
    | 'door-wide-open'
    | 'floor'
    | 'floor-large'
    | 'robot-arm-a'
    | 'robot-arm-b'
    | 'scanner-high'
    | 'scanner-low'
    | 'structure-corner-inner'
    | 'structure-corner-outer'
    | 'structure-doorway'
    | 'structure-doorway-wide'
    | 'structure-high'
    | 'structure-medium'
    | 'structure-short'
    | 'structure-tall'
    | 'structure-wall'
    | 'structure-window'
    | 'structure-window-wide'
    | 'structure-yellow-high'
    | 'structure-yellow-medium'
    | 'structure-yellow-short'
    | 'structure-yellow-tall'
    | 'top'
    | 'top-large';
};

export function getModelUrl<TRoot extends keyof ModelNameMap>(
  root: TRoot,
  slug: ModelNameMap[TRoot]
): string {
  return new URL(`../assets/models/${root}/${slug}.glb`, import.meta.url).href;
}
